### ISSUE TITLE
PPS2 PSC2016 Intro Presentation

### ISSUE THREAD

**Issue by alexchmykhalo** [PLLUG/pllug-presentation-system-2#14]
Create introductory presentation for the first PSC2016 meeting

**Comment by Guitarheroua** [comment]
[PLLUG Presentation System 2.0](https://docs.google.com/presentation/d/1AchZYvWH1r6ToJ_UevsIO5BzuRxabXZSKypiv2loWn8/edit?usp=drivesdk)
