### ISSUE TITLE
Investigation on Pandoc JSON AST format 

### ISSUE THREAD

**Issue by alexchmykhalo** [PLLUG/pllug-presentation-system-2#39]

**Comment by alexchmykhalo** [comment]
@SMHFandA Please, see created branch that conains test texts in tests/data/markdown folder. Install pandoc and convert them to JSON. Lets investigate structure of converted JSON files, so we will be able to parse them and use in our program.

**Comment by alexchmykhalo** [comment]
@pgmvp If you will have any problems - send me a message - do not spend hours if you could not do something.

**Comment by alexchmykhalo** [comment]
@SMHFandA  If you will have any problems - send me a message - do not spend hours if you could not do something.

**Comment by Guitarheroua** [comment]
@SMHFandA http://blogorama.nerdworks.in/converting-document-formats-with-pandoc/
Explanation and example on JavaScript, how to work with AST Pandoc JSON.

**Comment by Guitarheroua** [comment]
https://www.npmjs.com/package/pandox#a-collection-of-pandoc-extensions

**Comment by Guitarheroua** [comment]
https://hackage.haskell.org/package/pandoc-types-1.16.1/docs/Text-Pandoc-Definition.html
Official documentation.

**Comment by Guitarheroua** [comment]
@alexchmykhalo I will move this task to backlog, because we do not need JSON AST now, as we decided to work with HTML as intermediate format.
