### ISSUE TITLE
Presentation structure base classes

### ISSUE THREAD

**Issue by alexchmykhalo** [PLLUG/pllug-presentation-system-2#41]
Implement base classes that will represent presentation structure.

**Comment by Guitarheroua** [comment]
![PPS2_Scheme.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/PPS2_Scheme-2927c9eaaa64c61ffb8260256595945f81ffa0271316305a4f1621958aa26715.jpg)

**Comment by Guitarheroua** [comment]
![BasicElementsStructure.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/BasicElementsStructure-8f3ab216a0b929b8b75c3fdbab9b24cb112fb8b87627fa04555b08f265d6577c.jpg)
